### ISSUE TITLE
Error when trying to use an Interval for LocalTime

### ISSUE THREAD

**Issue by andrelfpinto** [gchudnov/mindthegap#39]
Hello,

Nice library!

I am getting this error when trying to use an `Interval` for `LocalTime`:

```
-- [E008] Not Found Error: ...
23 |  given Domain[LocalTime] = Domain.makeLocalTime(temporal.ChronoUnit.MINUTES)
   |                            ^^^^^^^^^^^^^^^^^^^^
   |value makeLocalTime is not a member of object com.github.gchudnov.mtg.Domain
1 error found
Compilation failed
```

Maybe it is because I can't download 1.0.1?

```
Downloading 4 dependencies
[error] .\project.scala:1:16
[error] Error downloading com.github.gchudnov:mtg_3:1.0.1
[error]   not found: ...
[error]   not found: https://repo1.maven.org/maven2/com/github/gchudnov/mtg_3/1.0.1/mtg_3-1.0.1.pom
[error]   not found: ...
[error]   No fallback URL found
[error] //> using dep "com.github.gchudnov::mtg:1.0.1"
[error]
```

**Comment by gchudnov** [comment]
Hi @andrelfpinto 
sorry for the breaking the build.
to be honest thought that no-one is using it :)

please wait a bit, I'll finish updating the library today the library and release it.

**Comment by andrelfpinto** [comment]
Hi, @gchudnov, there is no need to worry too much or to hurry, it's open source after all!

I am just starting to use it and probably the problem is me.

**Comment by gchudnov** [comment]
the build was fixed, 
![image](https://github.com/user-attachments/assets/9189c512-81d5-44e7-a598-f054fc5d5e5c)

but there still might be problems with method accessibility.

There are still some pending tasks:
- to recover examples
- update documentation
- update github actions
- release the library

can take some more time, but should be done till the end of the week.

**Comment by gchudnov** [comment]
@andrelfpinto 
The example for `LocalTime` was [added](https://github.com/gchudnov/mindthegap/blob/main/examples/src/main/scala/com/github/gchudnov/examples/CustomLocalTimeDomain.scala).

Still before publishing the library want to add more examples to see if the public API has any issues.

**Comment by gchudnov** [comment]
@andrelfpinto 

the library was published https://github.com/gchudnov/mindthegap/releases/tag/v2.0.0

if something is not working or there are any questions, please let me know

**Comment by gchudnov** [comment]
I'm closing then, if you have any problems with 2.0 please let me know
